service_out_of_memes:
  en: |-
    ๐ You've watched all the memes we've prepared for you! Come back tomorrow for MORE. ๐
  ru: |-
    ๐ ะขั ะฟะพัะผะพััะตะป ะฒัะต ะผะตะผั, ะบะพัะพััะต ะผั ะฟะพะดะณะพัะพะฒะธะปะธ ะดะปั ัะตะฑั! ะัะธัะพะดะธ ะทะฐะฒััะฐ, ะฟะพะบะฐะถะตะผ ะะฉะ. ๐
  uk: |-
    ๐ ะขะธ ะฟะตัะตะณะปัะฝัะฒ ะฒัั ะผะตะผะธ, ัะบั ะผะธ ะฟัะดะณะพััะฒะฐะปะธ ะดะปั ัะตะฑะต! ะัะธัะพะดั ะทะฐะฒััะฐ, ะฟะพะบะฐะถะตะผะพ ะะะะฌะจะ. ๐